truecharts/website

- docusaurus.config.js
> update docusaurus config

- docs/manual/SCALE Apps/Quick-Start Guides/01-Adding-TrueCharts.md
Signed-off-by: StevenMcElligott <89483932+StevenMcElligott@users.noreply.github.com>
Removed core train mention in Quick-Start
⚒️ Fixes  # 
**📃 Notes:**
---
> Remove core train from quick-start

- .github/workflows/gendocs.yaml
- .gitignore
This is some initial work aiming to move some of the docsgeneration (more precisely: security.md, in this case), to a daily cron on the website. Instead of running it everytime on App release...
**📃 Notes:**
---
> feat(docs): initial gendocs work

- docs/manual/SCALE Apps/Quick-Start Guides/01-Adding-TrueCharts.md
Signed-off-by: StevenMcElligott <89483932+StevenMcElligott@users.noreply.github.com>
Quick-start guide step 1 still had old references to trains that don't exist anymore, so deleted them 
⚒️ Fixes  # 
**📃 Notes:**
---
> Removed Core and Games references

- .github/workflows/gendocs.yaml
> update devcontainer which inclues update docgenerator

- docs/manual/SCALE Apps/Quick-Start Guides/14-backup-restore.md
> Adding warning for backup-restore page

- docs/about/contact.md
- docs/charts/stable/cloudflareddns/setup-guide.md
- docs/manual/SCALE Apps/Quick-Start Guides/01-Adding-TrueCharts.md
- docs/manual/SCALE Apps/Quick-Start Guides/02-Installing-an-App.md
- docs/manual/SCALE Apps/Quick-Start Guides/03-Edit-an-App.md
- docs/manual/SCALE Apps/Quick-Start Guides/04-Upgrade-rollback-delete-an-App.md
- docs/manual/SCALE Apps/Quick-Start Guides/05-add-storage.md
- docs/manual/SCALE Apps/Quick-Start Guides/06-linking-apps.md
- docs/manual/SCALE Apps/Quick-Start Guides/07-adding-letsencrypt.md
- docs/manual/SCALE Apps/Quick-Start Guides/08-installing-Traefik.md
- docs/manual/SCALE Apps/Quick-Start Guides/09-add-ingress.md
- docs/manual/SCALE Apps/Quick-Start Guides/10-add-middleware.md
- docs/manual/SCALE Apps/Quick-Start Guides/11-external-services.md
- docs/manual/SCALE Apps/Quick-Start Guides/12-vpn-setup.md
- docs/manual/SCALE Apps/Quick-Start Guides/13-docker-compose.md
> feat(docs): add link generator and fix some atributes

- docs/manual/SCALE Apps/Quick-Start Guides/12-vpn-setup.md
> fix(Docs) - remove .16 killswitch reference

- .github/workflows/gendocs.yaml
> add wf to copy single doc files

- docs/manual/SCALE Apps/Quick-Start Guides/00-Important-MUST-READ.md
Signed-off-by: Vincent Danen <vdanen@annvix.com>
Just a small typo I saw when reading.
> fix small typo

- docs/manual/FAQ.md
> feat(docs): add FAQ

- docs/manual/SCALE Apps/installing-Traefik.md
> Add text-based instructions to Installing Traefik

- docs/manual/SCALE Apps/Adding-TrueCharts.md
- docs/manual/SCALE Apps/linking-apps.md
- docs/manual/SCALE Apps/networking.md
- docs/manual/SCALE Apps/vpn-setup.md
docs tweaks across different pages:
- Reference latest VPN video instead of old outdated one
- Remove simple/nodeport references in networking
- Remove core train reference
- Add truetool to linking apps docs
markdownlint
**📃 Notes:**
- [ X] ⚖️ My code follows the style guidelines of this project
---
> docs updates: vpn,networking,trains,linking

- src/pages/index.js
- src/pages/index.module.css
The two buttons which are side-by-side on the homepage were not responsive. They sides were cut off on smaller displays.
This fix makes it so that the buttons are wrapped and displayed in a column layout. That way nothing gets cut off and the website looks good on smaller displays like phones.
⚒️ Fixes  # 
I tested the change locally with the development server in Chrome and Firefox.
> fix(website): Fixed responsiveness of buttons

- docs/manual/SCALE Apps/add-middleware.md
Since this guide has been expanded and move here (https://truecharts.org/docs/charts/stable/traefik/traefik-basicAuth-middleware) we don't need a page with a single video crowding the manual
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(Manual): Remove doubled middleware section

- docs/manual/SCALE Apps/backup-restore.md
Added some basic examples, if we add more I'd have to add the full install instructions haha.
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(Backup): Add Basic Backup examples

- docs/manual/SCALE Apps/app-install/add-ons.md
- docs/manual/SCALE Apps/app-install/application-config.md
- docs/manual/SCALE Apps/app-install/application-name.md
- docs/manual/SCALE Apps/app-install/controller.md
- docs/manual/SCALE Apps/app-install/documentation.md
- docs/manual/SCALE Apps/app-install/ingress.md
- docs/manual/SCALE Apps/app-install/networking.md
- docs/manual/SCALE Apps/app-install/resources-devices.md
- docs/manual/SCALE Apps/app-install/security.md
- docs/manual/SCALE Apps/app-install/storage.md
Section by section breakdown of our application install with explanations of the basics for each section with enough details for most basic users.
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(app-install): Create sections guide for apps

- docs/manual/options/add-ons.md
- docs/manual/options/advanced.md
- docs/manual/options/application-config.md
- docs/manual/options/application-name.md
- docs/manual/options/container-config.md
- docs/manual/options/controller.md
- docs/manual/options/documentation.md
- docs/manual/options/index.md
- docs/manual/options/ingress.md
- docs/manual/options/metrics.md
- docs/manual/options/networking.md
- docs/manual/options/resources-devices.md
- docs/manual/options/security.md
- docs/manual/options/storage.md
Quick cleanup and menu order
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(SCALE Config): Cleanup and menu order

- README.md
Signed-off-by: inmanturbo <47095624+inmanturbo@users.noreply.github.com>
⚒️ Fixes  issues with contributor submitting documentation PR's in the wrong place
Added `Contributing` section to README.md
**📃 Notes:**
---
> Add contributing note for docs location

- docusaurus.config.js
- src/pages/index.js
Fixed the frontpage link and the footer
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(links): Fixed a couple broken links

- news/2022-12-17-hostpath-validation.md
I'd also suggest a change for NFS to NFS share in this text, but thats my personal opinion.
Signed-off-by: Jesperbelt <70942135+Jesperbelt@users.noreply.github.com>
⚒️ Fixes  # 
**📃 Notes:**
---
> Small grammar fix

- docs/manual/systemrequirements.md
Add warning about HDD apps pool without small-blocks
> fix(sys-req): Update warning about HDD apps pool

- docs/manual/guides/Edit-an-App.md
- docs/manual/guides/Upgrade-rollback-delete-an-App.md
- docs/manual/guides/add-ingress.md
- docs/manual/guides/backup-restore.md
- docs/manual/guides/truenas-web-gui-via-traefik.md
Add links between guides where mentioned but not linked.  Minor fixes from having read through the documents and noticed a couple tiny errors were split into a separate commit.
⚒️ Fixes
Someone in Discord mentioned this being a problem... so I fixed what seemed obvious.  I'm sure someone with more context could actually do a good job polishing up the documentation.
Not at all.  But it's just Markdown.
**📃 Notes:**
I wasn't sure if there was a preference for links.  Embedded images used relative-to-the-site-root paths.  Some links used URLs that included a protocol and some were relative-to-the-site-root.  If there's a preference I'm happy to conform.
If this PR is an app addition …
> fix(docs): Minor fixes, link to referenced guides

- docusaurus.config.js
Fix the 3 footer links under the *Legal* heading.
⚒️ Fixes #96 
Tested that the links would work, did not render the project.
**📃 Notes:**
Change seemed trivial.
---
> fix: Update footer links

- docs/manual/guides/pvc-access.md
Signed-off-by: Jesperbelt <70942135+Jesperbelt@users.noreply.github.com>
⚒️ Fixes  # 
Video is not viewable, removing from the guide.
**📃 Notes:**
---
> Remove the video, link and mentions of the video.

- src/components/ChartsOverView/SearchBar.js
add an image before the searchbar.
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(searchbar) add image before the searchbar

- docs/manual/guides/sql-backup.md
Adding the info to create Postgres backups to the website so we can edit/modify and link to something concrete
⚒️ Fixes  # 
**📃 Notes:**
---
> feat(manual): Add Postgres Backup Script

- src/components/ChartsOverView/SearchBar.js
Signed-off-by: Jesperbelt <70942135+Jesperbelt@users.noreply.github.com>
⚒️ Fixes  # 
**📃 Notes:**
---
> [DocFix] Truecharts Icon on Chartlist search

- docs/manual/options/storage.md
Fixed a link still pointing at the old documentation location
Link works now 🙂
**📃 Notes:**
No functionality was changed at all, just a link in the documentation
> Update storage.md fixing a broken link in the docs

- docs/manual/SCALE/SUPPORT.md
- docs/manual/SCALE/guides/add-storage.md
- docs/manual/SCALE/guides/backup-restore.md
- docs/manual/SCALE/guides/linking-apps.md
- docs/manual/SCALE/guides/migration-pvc.md
- docs/manual/SCALE/guides/pvc-access.md
- docs/manual/SCALE/guides/scale-intro.md
- docs/manual/SCALE/guides/truenas-web-gui-via-traefik.md
- docs/manual/SCALE/guides/vpn-setup.md
Updates to the SCALE guides to fix some broken link/changed info
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(SCALEguides): Updated a bunch of links/info

- docs/manual/SCALE/guides/add-storage.md
- docs/manual/SCALE/guides/migration-pvc.md
Broken links fixed for pvc-guide
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(SCALEguide): Broken image links

- src/pages/index.js
> docfix | Url for the Truenas Scale button

- docs/manual/helm/common/README.md
- docs/manual/helm/common/container/README.md
- docs/manual/helm/common/container/fixedEnv.md
- docs/manual/helm/common/container/securityContext.md
> update some docs

- docs/charts/description_list.mdx
- src/components/ChartsOverView/HelperUtil.js
- src/components/ChartsOverView/SearchBar.js
Fix order of trains and remove redundant icon from searchbar component.
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(searchbar) remove icon + order of trains

- docs/manual/FAQ.md
- docs/manual/SCALE/guides/add-storage.md
- docs/manual/SCALE/guides/getting-started.md
- docs/manual/SCALE/guides/linking-apps.md
- docs/manual/SCALE/guides/scale-intro.md
- docs/manual/SCALE/guides/truenas-web-gui-via-traefik.md
- docs/manual/SUPPORT.md
- news/2022-12-17-hostpath-validation.md
- news/2023-02-10-nfs-docs.md
Fixing a lot of broken links after the recent changes to the navigation
-->
⚒️ Fixes  # 
**📃 Notes:**
---
> Fix broken links and reference NFS guide in news posts 

- docs/manual/helm/common/README.md
- docs/manual/helm/common/container/securityContext.md
> Update Docs for capabiltiies

- docs/manual/FAQ.md
Updated the FAQ and changed references of TrueTool to HeavyScript, including links.
Fixed some minor typos.
Changed the wording of some sections so it flows better.
⚒️ Fixes  # 
**📃 Notes:**
---
> Updated FAQ | TrueTool -> HeavyScript & Minors

- docs/manual/helm/common/scaleExternalInterface.md
> Update external Interfaces docs

- docs/manual/development/chart-yaml-structure.md
Fix broken link
⚒️ Fixes  # 
broken link to chart.yaml on Github
Checked link manually
**📃 Notes:**
---
> Update chart-yaml-structure.md - fix broken link

- docs/manual/SCALE/guides/pvc-migration-script.md
fix broken link to TT-migration github repo
⚒️ Fixes  # 
**📃 Notes:**
---
> fix broken migration script link

- docs/manual/FAQ.md
Several updates to improve readability and add extra info on FAQ page. Each commit has more detail.
⚒️ Fixes  # 
Proof reading
**📃 Notes:**
---
> FAQ page updates

- docs/manual/FAQ.md
- docs/manual/SUPPORT.md
- docs/manual/intro.md
Website changes to FAQ, Intro and Support pages
⚒️ Fixes  # 
Used docusaurus admonition markdown style on FAQ page.
**📃 Notes:**
Checked with mods the actual version being supported 22.12.0 to 22.12.2.
---
> Website changes

- docs/manual/helm/common/service/ExternalIP.md
> Add useSlice to docs

- docs/manual/FAQ.md
add faq entry re: apps that remain in a stopped state
⚒️ Fixes  # 
**📃 Notes:**
---
> feat(faq): add faq entry re stopped state

- docs/manual/SCALE/options/documentation.md
Correct display of checkbox on Documentation page
⚒️ Fixes  # 
Checkbox displayed as :checkbox:
Created "clone" website to review changed page(s) as it will be displayed on official website at https://truecharts-review.netlify.app
**📃 Notes:**
---
> Correct display of checkbox on Documentation page

- cspell.config.yaml
- docs/manual/FAQ.md
- docs/manual/SCALE/options/networking.md
> docs(SCALE): Add host-networking info

- docs/manual/FAQ.md
Add a FAQ about the issues of stopping Apps using the Stop button and the recommended methods and various warnings related to CNPG apps.
⚒️ Fixes  # 
Viewable at https://truecharts-review.netlify.app
Reviewed by several members of the team / moderators to ensure accuracy.
**📃 Notes:**
---
> Stop an app faq

- docs/manual/SCALE/options/resources-devices.md
update content and fix broken link
⚒️ Fixes  # 
fix broken link to Input Validation page
run website locally and tested link.
**📃 Notes:**
---
> Resources and Devices page - Update content and fix broken link

- docs/manual/development/chart-structure.md
Fix broken link on chart-structure.md page
⚒️ Fixes  # 
broken link to https://wiki.truecharts.org/development/questions-yaml/
**📃 Notes:**
---
> Chart structure - fix broken link

- news/2023-05-16-stop-all.md
It happened to me and I thought that this note could help people to not get into the same error as me.
⚒️ Fixes  # 
**📃 Notes:**
---
> Added uncheck box note.

- docs/manual/SCALE/guides/migration-pvc.md
Mention HeavyScript 2.0.0+ as an option for scaling down the apps.
⚒️ Fixes  # 
**📃 Notes:**
---
> Update migration-pvc.md | HeavyScript to scale down apps

- news/2023-07-03-operator-changes.md
- news/authors.yml
Blog post about operators as requested by @Ornias1993 
⚒️ Fixes  #
**📃 Notes:**
---
> news(operators): operators blog post

- docs/manual/SCALE/guides/pvc-migration-script.md
migration script - remove unnecessary dataset creation step
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(docs): migration script - remove unnecessary dataset creation

- cspell.config.yaml
- docs/manual/SCALE/guides/getting-started.md
Possibly fix the resized icons (last chance before I photoshop myself) and add info about the Prometheus operator inside the Quick-Start
⚒️ Fixes  # 
**📃 Notes:**
---
> feat(Quick-Start): Add Prometheus info

- docs/manual/helm/common/README.md
- docs/manual/helm/common/webhook.md
> chore(docs): add webhook docs

- news/2023-07-20-cert-manager-operator.md
Add a blog post about addition of cert-manager operator
⚒️ Fixes  # 
**📃 Notes:**
---
> news(cert-manager): cert-manager blog post

- docs/manual/SCALE/guides/sql-export.md
Remove tcdbbackup.sh 
⚒️ Fixes  #
**📃 Notes:**
---
> docs(sql-export): remove tcdbbackup

- src/pages/sponsor.md
Added info about Open Collective and added more links for @stavros-k , @xstar97 and me.
⚒️ Fixes  # 
**📃 Notes:**
---
> update(Sponsors): Update info

- src/pages/sponsor.md
> Update sponsor url

- docs/manual/FAQ.md
Add operators to FAQ.
⚒️ Fixes  #
**📃 Notes:**
---
> docs(faq): add operators

- docs/manual/FAQ.md
- docs/manual/SUPPORT.md
- docs/manual/scope.md
- docs/manual/systemrequirements.md
> fix(menu): Add Scope to menu and fix order

- src/pages/sponsor.md
Cleaned up the text and returned GitHub Sponsors and Patreon
⚒️ Fixes  # 
**📃 Notes:**
---
> feat(sponsors): Return Patreon + GitHub

- .github/workflows/deploy.yaml
- docusaurus.config.js
- package.json
- src/pages/store/index.mdx
- src/pages/store/product.mdx
- yarn.lock
> Update docusauru+react+mdx and apply minification

- docs/manual/FAQ.md
- docs/manual/SCALE/guides/getting-started.md
- docs/manual/SUPPORT.md
- docs/manual/scope.md
- docs/manual/systemrequirements.md
- news/2023-05-24-traefik-changes.md
- news/2023-06-01-metallb-changes.md
- news/2023-06-04-cnpg-changes.md
- news/2023-07-03-operator-changes.md
- news/2023-07-20-cert-manager-operator.md
>  Fixing broken links, spelling/grammar, updating instructions

- docs/manual/SCALE/guides/linking-apps.md
Remove the broken generator.
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(internal-domain): remove broken generator

- docs/manual/SCALE/guides/getting-started.md
- package.json
- yarn.lock
Fixed 7 spelling errors in the "Getting Started with TrueCharts" SCALE guide.
I noticed when I was reading through the docs that there were a couple of spelling errors, so, I thought I would try to contribute. First timer so apologies if I miss anything.
⚒️ Fixes  # Changed "stricktly" to "strictly" and changed "optiona" to "optional" _edit:_ Added more spelling fixes to getting-started.md
No tests performed. Just some spelling error fixes.
> Fix various spelling errors in getting-started.md

- docs/charts/common/index.md
- docs/manual/FAQ.md
- docs/manual/SUPPORT.md
- docusaurus.config.js
- news/2023-06-01-metallb-changes.md
- news/2023-06-04-cnpg-changes.md
- news/2023-07-03-operator-changes.md
- src/pages/contact.html
- src/pages/contact.md
- src/theme/Navbar/Content/index.js
- static/_redirects
> fix(website) fix social links

- src/pages/sponsor.md
- static/_redirects
> feat(website) new links and update sponsors

- docs/manual/FAQ.md
Adds command to check for existing CNPG databases.
⚒️ Fixes  #
**📃 Notes:**
---
> docs(faq): cnpg operator update

- docs/manual/SCALE/guides/vpn-setup.md
⚒️ Fixes  # updates link to Glueton wiki
It's just an small change, from old https://github.com/qdm12/gluetun/wiki to new wiki https://github.com/qdm12/gluetun-wiki
**📃 Notes:**
---
> fix: link for gluetun wiki updated

- news/2023-11-05-cluster-wide-certificates.md
⚒️ Fixes  # The link to the chart docs in the recent news post about Cluster-Wide Certificates.
Via github markdown preview
**📃 Notes:**
---
> fix: link to docs in Cluster-Wide Certificates news updated

- docs/manual/helm/common/README.md
- docs/manual/helm/common/container/README.md
- docs/manual/helm/common/workload/cronjob.md
- docs/manual/helm/common/workload/daemonset.md
- docs/manual/helm/common/workload/job.md
- docs/manual/helm/common/workload/statefulset.md
Fixes link errors.
⚒️ Fixes  #
**📃 Notes:**
---
> fix(docs): fix link errors

- news/2023-11-11-stability-tiers-and-helm.md
> grammar check on 2023-11-11 news article

- news/2023-11-18-end-of-container-mirroring.md
- news/authors.yml
> feat(news): Add news about end of cont mirror

- news/2023-11-18-end-of-container-mirroring.md
> fix(news): Formatting/typos to Containers post

- news/2023-11-18-end-of-container-mirroring.md
Fixes slug for mirroring blog post.
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(blog): update slug

- docs/manual/SCALE/guides/dataset.mdx
Fix build error
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(dataset): fix build error

- docs/manual/SCALE/guides/dataset.mdx
Fixes missing `
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(dataset): fix missing `

- news/2023-12-09-january-2024-changes-preview.md
Remove space to fix space
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(news): Fix typo

- news/2023-12-19-holiday-wishes-and-updates.md
> news(holidays): 2023 holiday post

- news/2023-12-25-homepage-integration/index.md
> grammar check on 2023-12-25 news article

- news/2023-12-31-ai-support.md
> update TrueAI news message

- docs/manual/helm/common/container/probes.md
- docs/manual/helm/common/fallbackDefaults.md
- docs/manual/helm/common/global.md
- docs/manual/helm/common/index.md
- docs/manual/helm/common/persistence/index.md
- docs/manual/helm/common/persistence/pvc-vct/index.md
- docs/manual/helm/common/service/index.md
- docs/manual/helm/common/service/ports.md
- docs/manual/helm/common/workload/daemonset.md
- docs/manual/helm/common/workload/deployment.md
> link to defaults

- cspell.config.yaml
- docs/manual/helm/common/index.md
- docs/manual/helm/common/podOptions.md
- docs/manual/helm/common/workload/index.md
> common docs

- docs/manual/FAQ.md
- docs/manual/SCALE/guides/common-errors.md
- docs/manual/SCALE/guides/linking-apps.md
- docs/manual/SCALE/guides/vpn-setup.md
- news/2023-12-20-persistence-changes.md
Docs updates
- VPN Gluetun wiki links
- Heavyscript dns command
- FAQ apps requiring ingress
- FAQ remove bluefin specific questions (ie host path validation)
- Statefulset codeblock formatting
- Add common errors page
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(docs): cleanup vpn, faq, linking apps, statefulset, add common errors page

- docs/manual/SUPPORT.md
> fix(Support): Re-sync Website to GitHub

- cspell.config.yaml
- docs/manual/SCALE/guides/common-errors.md
> formatting

- docs/manual/SCALE/guides/common-errors.md
- add operators delete solutions directly onto common errors page to aid TrueAI parsing (instead of just linking to FAQ)
- add instructions for statefulset delete
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(common errors): add operator solutions directly onto page

- docs/manual/FAQ.md
- docs/manual/SCALE/guides/getting-started.md
- docs/manual/SCALE/guides/recover-cnpg.md
- docs/manual/SCALE/options/add-ons.md
- docs/manual/SCALE/options/networking.md
- docs/manual/SCALE/options/storage.md
Docs updates
- getting started tweaks
- configuration section updates (addons, storage)
- cnpg FAQ remove outdated warning
- cnpg recover doc remove outdated safe reboot section
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(docs): update cnpg faq and cnpg recover, configuration, getting started

- docs/manual/helm/common/container/resources.md
- docs/manual/helm/common/resources.md
> fix resources

- docs/manual/FAQ.md
- docs/manual/SCALE/guides/getting-started.md
- docs/manual/intro.md
- docs/manual/scope.md
> Test if we can add more inpage ads

- docs/manual/SCALE/guides/dragonfish-storage.md
> Minor fixes

- news/2024-03-16-train-renames.md
Needs to wait till @stavros-k is done with verifying the DragonFish storage compatibility
**📃 Notes:**
---
> add train rename news

- docs/manual/FAQ.md
- docs/manual/SCALE/guides/getting-started.md
> Update SCALE operator instructions

- docs/manual/SCALE/SUPPORT.md
> Update SCALE support policy

- docs/manual/helm/guides/add-ingress.md
- docs/manual/helm/guides/add-storage.md
- docs/manual/kubeapps/SUPPORT.md
- docs/manual/kubeapps/intro.md
> Minor updates to non-SCALE docs

- docs/manual/SCALE/intro.md
⚒️ Fixes  # 
broken link
**📃 Notes:**
- [*] 👀 I have performed a self-review of my own code
---
> fixes broken link to kubeapps intro page

- docs/manual/SCALE/guides/getting-started.md
⚒️ Fixes  # 
couple small typos in the guide
**📃 Notes:**
- [*] 👀 I have performed a self-review of my own code
---
> couple small typos fixed

- docusaurus.config.js
> Update broken Support Policy link, replace with Project Scope

- docs/charts/stable/portainer-ce/installation-notes.md
- docs/manual/SCALE/guides/backup-restore.md
- docs/manual/SCALE/guides/dragonfish-storage.md
- docs/manual/SCALE/guides/getting-started.md
- docs/manual/SCALE/guides/migration-pvc.md
- docs/manual/SCALE/guides/nfs-share.md
- docs/manual/SCALE/guides/pvc-migration-script.md
- docs/manual/SCALE/guides/scale-intro.md
- docs/manual/SCALE/guides/truenas-web-gui-via-traefik.md
- docs/manual/SCALE/guides/velero-minio-heavyscript-backup-restore.md
- docs/manual/SCALE/guides/vpn-setup.md
- news/2023-02-20-ix-christmas/index.md
- news/2023-03-06-breaking-enterprise-changes/index.md
- news/2023-12-25-homepage-integration/index.md
- news/2024-02-24-small-scale-changes/2024-02-24-small-scale-changes.md
> Replaces (img/...) with (./img/...) on non-chart docs

- package-lock.json
- src/assets/charts.json
- src/components/chart-list/AllCharts.astro
- src/components/chart-list/Filter.astro
- src/components/chart-list/TrainCharts.astro
- src/components/chart-list/TrainList.astro
- src/components/chart-list/utils.ts
- src/content/docs/charts/description-list.md
- src/content/docs/charts/description-list.mdx
> add chart-list

- src/components/RoundIcon.astro
> force github avatars as jpg for cloudflare optimalisation

- astro.config.mjs
- src/components/RoundIcon.astro
- src/components/chart-list/ChartImage.astro
- src/components/chart-list/TrainCharts.astro
> optimizations

- astro.config.mjs
> enable post-render optimisation for everything except html

- astro.config.mjs
> change compres order

- astro.config.mjs
- src/components/Navigation.astro
- src/pages/index.astro
> dont use 308 on menus to prevent prefetch on external links

- src/content/docs/404.md
- src/content/docs/platforms/SCALE/migrations/_category_.yaml
> Add category yaml for migrations

- public/openebsmv.sh
in openebsmv.sh script, changes `kubectl` to `k3s kubectl` 
(openebsmv.sh is just for SCALE users migrating from cobia to dragonfish)
- [x ] 🪛 Bugfix
**📃 Notes:**
---
> fix(openebsmv.sh): change kubectl to k3s kubectl

- src/components/CustomHeader.astro
- src/components/CustomHero.astro
- src/pages/index.astro
> fix layout shift and searchb ar on all devices

- src/content/docs/news/2024-04-22-new-website.md
> New website news post

- src/content/docs/news/2024-04-21-new-website.md
Update date
⚒️ Fixes  # 
**📃 Notes:**
---
> Update and rename 2024-04-22-new-website.md to 2024-04-21-new-website.md

- src/content/docs/fluxcd/index.md
- src/content/docs/helm/index.md
> update helm docs and add fluxcd intro example

- src/content/docs/SCALE/SUPPORT.md
Fixes aside formatting.
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(support): fix aside

- src/content/docs/SCALE/migrations/cobia-dragonfish.md
> Add one-line bash script to DragonFish migration guide

- src/content/docs/SCALE/migrations/cobia-dragonfish.mdx
Indent everything under steps so build is successful.
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(dragonfish-guide): indent steps

- src/content/docs/news/2024-04-23-dragonfish-release.mdx
Fixes steps
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(dragonfish-news): fix steps

- src/content/docs/news/2024-04-23-dragonfish-release.mdx
Fixes steps typo.
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(dragonfish-news): fix steps typo

- src/content/docs/news/2024-04-23-dragonfish-release.mdx
Aside was not indented enough causing issue with steps.
⚒️ Fixes  # 
Tested this on my own docs.
**📃 Notes:**
---
> fix(dragonfish-news): fix indent on aside

- src/content/docs/news/2024-04-23-dragonfish-release.mdx
Switches dragonfish news post to new steps format.
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(dragonfish-news): new steps format

- astro.config.mjs
- package-lock.json
- package.json
- src/components/Navigation.astro
- src/components/multi-icons/MultiIcons.astro
- src/content/docs/SCALE/migrations/cobia-dragonfish.mdx
- src/pages/index.astro
- src/tailwind.css
- tailwind.config.ts
> fix(styles): use the correct tailwind plugin/setup

- src/content/docs/SCALE/guides/common-errors.md
- src/content/docs/SCALE/guides/vpn-setup.md
- fix two vpn setup guide images
- update the postgres version common errors solution now that the field is in the UI
- 
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(vpn setup and common errors): small updates

- src/content/docs/SCALE/migrations/cobia-dragonfish.mdx
> Clarify OpenEBS dataset location

- src/content/docs/SCALE/migrations/cobia-dragonfish.mdx
> Update migration guide

- src/content/docs/SCALE/migrations/cobia-dragonfish.mdx
Fix aside
⚒️ Fixes  # 
**📃 Notes:**
---
> fix(dragonfish-guide) fix aside

- .github/workflows/cloudflare.yaml
> increase node ram/cache size

- src/content/docs/SCALE/migrations/cobia-dragonfish.mdx
- Instructs users to backup with HeavyScript prior to updating
- Adds an explicit update step to the guide
- Adds instructions for restoring a CNPG database via the backup as part of the migration script.
Currently no instructions are provided in the migration script for performing a backup with HeavyScript.  I did this before following the guide and it ended up being helpful and required to complete it!  I figure it's best if this is explicitly part of the instructions instead of hoping that they follow general best practices when updating & migrating things.
This is a generalization of the steps that I went through when migrating Nextcloud on my personal server.  Instructions given were helpfully provided by @ksimm1 …
> docs: Adds a backup step to the DragonFish migration guide

- src/content/docs/SCALE/guides/backup-restore.md
> Add warning to restoration section about SCALE OpenEBS bug

- src/content/docs/SCALE/guides/backup-restore.md
> Adds link to OpenEBS upstream issue

- src/content/docs/news/2024-05-30-scale-deprecation.md
> Minor fixes to 2024-05-30-scale-deprecation.md

- astro.config.mjs
- src/content/docs/clustertool/designdoc.md
- src/content/docs/clustertool/functions/genconfig.md
- src/content/docs/clustertool/functions/init.md
- src/content/docs/clustertool/index.md
> add initial clustertool docs and cleanup things a tad

- src/content/docs/guides/code-server.md
> CodeServer Guide

- src/content/docs/guides/linking-apps.md
> Changes to  include proper Namespaces and replace "variables"

- src/content/docs/clustertool/getting-started.md
- src/content/docs/clustertool/migrations/scale.md
> Add clustertool getting-started

- src/content/docs/common/global.md
- src/content/docs/common/ingress/traefik.md
> docs(commontraefik): remove enableFixedMiddlewares key from global

- src/content/docs/clustertool/migrations/scale.md
* Added Links to Permission Guide and NFS Setup Guide
* Added Link to VolSync Guide
⚒️ Fixes  # 
**📃 Notes:**
---
>  Update scale.md with links to guides

- src/content/docs/deprecated/SCALE/index.mdx
Clarify that the OpenEBS dataset should not be encrypted.
> Unencrypted dataset for OpenEBS

- src/content/docs/guides/linking-apps.md
> Clarification on linking apps naming scheme

- src/content/docs/common/credentials.md
encrKey is a required field but docs stated "when needed"
⚒️ Fixes  # 
**📃 Notes:**
---
> Update credentials.md - Update Doc to match required field for EncKey

- src/content/docs/clustertool/designdoc.md
- src/content/docs/clustertool/functions/apply.md
- src/content/docs/clustertool/functions/bootstrap.md
- src/content/docs/clustertool/functions/checkcrypt.md
- src/content/docs/clustertool/functions/decrypt.md
- src/content/docs/clustertool/functions/encrypt.md
- src/content/docs/clustertool/functions/genconfig.md
- src/content/docs/clustertool/functions/init.md
- src/content/docs/clustertool/getting-started.md
- src/content/docs/clustertool/index.md
- src/content/docs/clustertool/migrations/scale.md
- src/content/docs/clustertool/virtual-machines/proxmox.md
- src/content/docs/clustertool/virtual-machines/truenas-scale.md
- src/content/docs/clustertool/virtual-machines/unraid.md
- src/content/docs/clustertool/virtual-machines/virtualbox.md
- src/content/docs/guides/add-ingress.md
- src/content/docs/guides/add-service.md
- src/content/docs/guides/add-storage.md
- src/content/docs/guides/code-server.md
- src/content/docs/guides/external-service.md
- src/content/docs/guides/index.md
- src/content/docs/guides/linking-apps.md
- src/content/docs/guides/s3-setup.md
- src/content/docs/guides/volsync-backup-restore.md
- src/content/docs/guides/vpn-setup.md
Minor updates to new docs
⚒️ Fixes  # 
**📃 Notes:**
---
> chore: Migration docs

- src/content/docs/clustertool/virtual-machines/virtualbox.md
Adds instructions for commenting out qemu-guest-agent when using virtualbox.
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(clustertool): add clustertool instruction for virtualbox

- src/content/docs/common/persistence/hostPath.md
Add mountPath to hostPath example.
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(common): add mountpath

- src/content/docs/general/support-policy.md
- src/content/docs/news/2024-07-05-clustertool-public-alpha.md
> ClusterTool Alpha News Post and Minor Updates to Support Policy

- src/content/docs/deprecated/SCALE/SUPPORT.md
- src/content/docs/deprecated/SCALE/guides/add-storage.md
- src/content/docs/deprecated/SCALE/guides/backup-restore.md
- src/content/docs/deprecated/SCALE/guides/cnpg-migration-guide.md
- src/content/docs/deprecated/SCALE/guides/dataset.md
- src/content/docs/deprecated/SCALE/guides/linking-apps.md
- src/content/docs/deprecated/SCALE/guides/migration-pvc.md
- src/content/docs/deprecated/SCALE/guides/nfs-share.md
- src/content/docs/deprecated/SCALE/guides/pci-passthrough.md
- src/content/docs/deprecated/SCALE/guides/pvc-access.md
- src/content/docs/deprecated/SCALE/guides/questions-yaml.md
- src/content/docs/deprecated/SCALE/guides/recover-cnpg.md
- src/content/docs/deprecated/SCALE/guides/scale-intro.mdx
- src/content/docs/deprecated/SCALE/guides/sql-export.md
- src/content/docs/deprecated/SCALE/guides/truenas-web-gui-via-traefik.md
- src/content/docs/deprecated/SCALE/guides/vpn-setup.md
- src/content/docs/deprecated/SCALE/index.mdx
- src/content/docs/deprecated/SCALE/migrations/cobia-dragonfish.mdx
- src/content/docs/deprecated/SCALE/systemrequirements.md
- src/content/docs/deprecated/SCALE/validation.md
> Update SCALE docs to remove catalogue install options and add a deprecation notice to all SCALE guides

- src/content/docs/clustertool/virtual-machines/systemrequirements.md
> Minor update to VM system requirements

- src/content/docs/general/support-policy.md
> fix:Update support-policy.md to correctly reflect Helm and not TrueNAS

- src/content/docs/general/fluxcd.md
Reverts truecharts/website#793
> Revert "Full example for flux deployment"

- src/content/docs/news/2024-08-22-scale-faq.md
Fix grammar.
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(scale-faq): fix grammar

- src/content/docs/news/2024-08-22-scale-faq.md
> Additional clarifications for SCALE FAQ

- src/content/docs/news/2024-08-22-scale-faq.md
> scale-faq: update wording

- src/content/docs/common/ingress/traefik.md
This pull request fixes a copy/paste error for the traefik ingress integration documentation.
**📃 Notes:**
---
> docs(ingress): amend traefik ingress integration reference.

- src/content/docs/clustertool/virtual-machines/truenas-scale.mdx
> Update Talos ISO url

- src/content/docs/clustertool/csi/democratic.md
- src/content/docs/clustertool/csi/index.md
> Initial Stuff for Democratic CSI guide

- src/content/docs/clustertool/csi/topolvm.md
Adds a draft of a guide for setting up TopoLVM on a single node cluster.
⚒️ Fixes  #N/A
I think it's right from what I remember. I'll go through the steps again when the ClusterTool RC comes out
**📃 Notes:**
I don't have any prior Kubernetes experience other than reading the TrueCharts discord and messing around with ClusterTool.
> add TopoLVM CSI guide

- src/content/docs/clustertool/getting-started.md
Fixes some outdated info with getting started guide.
⚒️ Fixes  # 
**📃 Notes:**
---
> docs(clustertool): cleanup getting started guide
